name: Centrifuged
favicon: null
layout_spectrum: 0.6418526214547455
typography_spectrum: 0.71948
title: 'Serious Designs, Fun Technology, Amateur Science and Okay Humor'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfbff'
    - '#bfb4ba'
    - '#9d8c92'
    - '#695e66'
    - '#482d3e'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.05636655259877443
purpose: []
